Fix x_inputs Empty Array in List ValueError
Under certain random seeds I've found `x_inputs` to have the value:
```
[array([], shape=(0, 5), dtype=float64)]
```

This has a length of 1 which will pass the `len(x_inputs)` check but raise an error on 
```
self.track_grip_model_x.fit(x_inputs_all, x_targets_all)
```
ValueError: Found array with 0 sample(s) (shape=(0, 5)) while a minimum of 1 is required.

Adding another check to see if `len(np.vstack(x_inputs))` is 0 solves this problem.